### ISSUE TITLE
Cody: Fix hyperlinked images

### ISSUE THREAD

**Issue by pgoggles** [Team-Fourtitude/HR-FEC#26]
https://github.com/Team-Fourtitude/HR-FEC/blob/53229ba411dcbda9d8d8577481bd1762b1b7a254/client/src/components/cody/Description.jsx#L23

Look into using FontAwesome or React-Icons or even hosting these images in your client/public folder, while this works now, you do not know if this website will exist in a month or so, and then your page would have a bunch of broken image hyperlinks

**Comment by Cosze** [comment]
all good now
