### ISSUE TITLE
Cody: Test File

### ISSUE THREAD

**Issue by pgoggles** [Team-Fourtitude/HR-FEC#33]
https://github.com/Team-Fourtitude/HR-FEC/blob/53229ba411dcbda9d8d8577481bd1762b1b7a254/client/src/components/cody/Test.jsx#L1-L26

I am not sure of the purpose of this file, is it for testing or is it for you to test if your page is working? I believe the correct naming if you are trying to make a test file (for Jest, for example) would be name.test.js if the original file was name.js

**Comment by Cosze** [comment]
this was a file to test if the page worked with the server set up will be removed from the main repo soon
